### ISSUE TITLE
[Event]: COSCUP

### ISSUE THREAD

**Issue by leafoliage** [Koyingtw/cs-events#1]
### 活動名稱

COSCUP 開源人年會

### 活動時間

2023-07-29 ~ 2023-07-30

### 活動地點

國立臺灣科技大學

### 詳細資訊

[活動網址](https://coscup.org/2023/zh-TW/landing)

COSCUP 是由台灣開放原始碼社群聯合推動的年度研討會，起源於 2006年，是台灣自由軟體運動（FOSSM）重要的推動者之一。活動包括有講座、攤位、社團同樂會等，除了邀請國際的重量級演講者之外，台灣本土的自由軟體推動者也經常在此發表演說，會議的發起人、工作人員與講者都是志願參與的志工，所有議程都是免費參加。

（活動資訊來自 COSCUP 官網）

**Comment by Koyingtw** [comment]
已更新，感謝！
