### ISSUE TITLE
[Event]: PyCon

### ISSUE THREAD

**Issue by hlc23** [Koyingtw/cs-events#2]
### 活動名稱

PyCon / Python 年會

### 活動時間

2023-09-02 10:00 ~ 18:00 與 2023-09-03 09:00 ~ 18:00

### 活動地點

中央研究院人文社會科學館 - 115 臺北市南港區研究院路二段 128 號人文社會科學館

### 詳細資訊

https://tw.pycon.org/2023/zh-hant

**Comment by Koyingtw** [comment]
已新增！
