### ISSUE TITLE
2023 清大網站開發實務集訓營

### ISSUE THREAD

**Issue by michellechang2006** [Koyingtw/cs-events#3]
### 活動名稱

2023 清大網站開發實務集訓營

### 活動時間

第一梯 2023/07/17（一）–　2023/07/19（三） 第二梯 2023/07/31（一）– 2023/08/02（三）8:30 - 21:00

### 活動地點

線上舉辦

### 詳細資訊

報名連結:https://tinyurl.com/2n3l47cc

主辦單位：清華大學資訊科學研習社 NTHU Tech Society
活動詳情：https://webcamp.nthu.dev

**Comment by Koyingtw** [comment]
已新增！
